# 太上老君AI平台 - 高级AI功能性能优化配置

# 服务器配置
server:
  # HTTP服务器配置
  http:
    port: 8080
    read_timeout: 30s
    write_timeout: 30s
    idle_timeout: 120s
    max_header_bytes: 1048576  # 1MB
    
  # 连接池配置
  connection_pool:
    max_idle_conns: 100
    max_idle_conns_per_host: 10
    idle_conn_timeout: 90s
    
  # 请求限制
  limits:
    max_request_size: 10485760  # 10MB
    max_response_size: 52428800  # 50MB
    max_concurrent_requests: 1000
    request_timeout: 300s

# AGI能力配置
agi:
  # 性能参数
  performance:
    max_concurrent_tasks: 50
    task_timeout: 300s
    reasoning_depth_limit: 10
    planning_horizon_limit: 20
    creativity_iterations: 5
    
  # 缓存配置
  cache:
    enable: true
    ttl: 3600s  # 1小时
    max_size: 1000
    cleanup_interval: 300s  # 5分钟
    
  # 资源限制
  resources:
    max_memory_per_task: 1073741824  # 1GB
    max_cpu_time_per_task: 60s
    max_gpu_memory_per_task: 2147483648  # 2GB
    
  # 优化策略
  optimization:
    enable_parallel_processing: true
    enable_result_caching: true
    enable_incremental_reasoning: true
    enable_early_stopping: true
    confidence_threshold: 0.8

# 元学习引擎配置
meta_learning:
  # 性能参数
  performance:
    max_concurrent_sessions: 20
    session_timeout: 1800s  # 30分钟
    max_episodes_per_session: 1000
    max_data_samples: 10000
    
  # 内存管理
  memory:
    enable_memory_replay: true
    replay_buffer_size: 100000
    memory_cleanup_threshold: 0.8
    memory_compression: true
    
  # 学习优化
  learning:
    adaptive_learning_rate: true
    early_stopping_patience: 10
    gradient_clipping: true
    batch_size_adaptation: true
    
  # 策略配置
  strategies:
    gradient_based:
      learning_rate: 0.001
      momentum: 0.9
      weight_decay: 0.0001
      
    model_agnostic:
      inner_steps: 5
      outer_steps: 100
      meta_lr: 0.01
      
    few_shot:
      shots: 5
      ways: 3
      episodes: 1000
      
    transfer_learning:
      freeze_layers: 0.5
      fine_tune_epochs: 10
      domain_adaptation: true

# 自我进化系统配置
self_evolution:
  # 性能参数
  performance:
    max_concurrent_evolutions: 10
    evolution_timeout: 7200s  # 2小时
    max_population_size: 100
    max_generations: 1000
    
  # 计算资源
  compute:
    enable_distributed_evolution: true
    worker_nodes: 4
    parallel_evaluations: true
    gpu_acceleration: true
    
  # 进化策略
  strategies:
    genetic:
      population_size: 50
      generations: 100
      mutation_rate: 0.1
      crossover_rate: 0.8
      selection_pressure: 2.0
      elite_ratio: 0.1
      
    neuro_evolution:
      network_complexity_limit: 1000
      connection_mutation_rate: 0.3
      node_mutation_rate: 0.1
      weight_mutation_rate: 0.8
      
    gradient_free:
      sigma: 0.1
      learning_rate: 0.01
      population_size: 100
      
  # 优化目标
  optimization:
    multi_objective: true
    pareto_front_size: 20
    convergence_threshold: 0.001
    diversity_preservation: true

# 混合模式配置
hybrid:
  # 能力协调
  coordination:
    enable_capability_fusion: true
    fusion_strategy: "weighted_average"
    confidence_weighting: true
    adaptive_routing: true
    
  # 负载均衡
  load_balancing:
    strategy: "round_robin"  # round_robin, least_connections, weighted
    health_check_interval: 30s
    failure_threshold: 3
    recovery_timeout: 60s
    
  # 结果聚合
  aggregation:
    consensus_threshold: 0.7
    max_voting_rounds: 3
    conflict_resolution: "highest_confidence"

# 监控和指标
monitoring:
  # 性能指标
  metrics:
    enable: true
    collection_interval: 10s
    retention_period: 7d
    aggregation_window: 1m
    
  # 健康检查
  health_check:
    interval: 30s
    timeout: 5s
    failure_threshold: 3
    success_threshold: 2
    
  # 告警配置
  alerts:
    enable: true
    cpu_threshold: 0.8
    memory_threshold: 0.85
    response_time_threshold: 5s
    error_rate_threshold: 0.05
    
  # 日志配置
  logging:
    level: "info"  # debug, info, warn, error
    format: "json"
    max_size: 100MB
    max_backups: 10
    max_age: 30d
    compress: true

# 缓存系统
cache:
  # Redis配置
  redis:
    enable: true
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    pool_size: 100
    min_idle_conns: 10
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    
  # 本地缓存
  local:
    enable: true
    max_size: 1000
    ttl: 300s
    cleanup_interval: 60s
    
  # 缓存策略
  strategy:
    write_through: true
    write_behind: false
    cache_aside: true
    refresh_ahead: true

# 数据库配置
database:
  # 连接池
  connection_pool:
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_lifetime: 3600s
    conn_max_idle_time: 300s
    
  # 查询优化
  query:
    timeout: 30s
    slow_query_threshold: 1s
    enable_query_cache: true
    cache_size: 1000
    
  # 事务配置
  transaction:
    isolation_level: "READ_COMMITTED"
    timeout: 60s
    retry_attempts: 3
    retry_delay: 1s

# 安全配置
security:
  # 认证
  authentication:
    enable: true
    jwt_secret: "${JWT_SECRET}"
    token_expiry: 3600s
    refresh_token_expiry: 86400s
    
  # 授权
  authorization:
    enable: true
    rbac: true
    permission_cache_ttl: 300s
    
  # 限流
  rate_limiting:
    enable: true
    requests_per_minute: 1000
    burst_size: 100
    cleanup_interval: 60s
    
  # CORS
  cors:
    enable: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    max_age: 86400s

# 网络配置
network:
  # 超时设置
  timeouts:
    dial_timeout: 10s
    keep_alive: 30s
    tls_handshake_timeout: 10s
    expect_continue_timeout: 1s
    
  # 重试策略
  retry:
    max_attempts: 3
    initial_delay: 1s
    max_delay: 30s
    backoff_multiplier: 2.0
    
  # 压缩
  compression:
    enable: true
    level: 6  # 1-9
    min_size: 1024

# 资源管理
resources:
  # CPU配置
  cpu:
    max_cores: 0  # 0表示使用所有可用核心
    affinity: []  # CPU亲和性设置
    
  # 内存配置
  memory:
    max_heap_size: "4g"
    gc_target_percentage: 100
    gc_max_pause: 10ms
    
  # GPU配置
  gpu:
    enable: true
    devices: []  # 空表示使用所有可用GPU
    memory_fraction: 0.8
    
  # 磁盘配置
  disk:
    temp_dir: "/tmp/taishanglaojun"
    max_temp_size: "10g"
    cleanup_interval: 3600s

# 开发和调试
development:
  # 调试模式
  debug:
    enable: false
    profiling: false
    trace: false
    
  # 热重载
  hot_reload:
    enable: false
    watch_dirs: ["./"]
    ignore_patterns: ["*.log", "*.tmp"]
    
  # 测试配置
  testing:
    mock_external_services: false
    test_data_dir: "./testdata"
    parallel_tests: true

# 部署配置
deployment:
  # 环境
  environment: "production"  # development, staging, production
  
  # 健康检查
  health_check:
    startup_probe:
      initial_delay: 30s
      period: 10s
      timeout: 5s
      failure_threshold: 3
      
    liveness_probe:
      initial_delay: 60s
      period: 30s
      timeout: 5s
      failure_threshold: 3
      
    readiness_probe:
      initial_delay: 10s
      period: 5s
      timeout: 3s
      failure_threshold: 3
  
  # 扩缩容
  scaling:
    min_replicas: 1
    max_replicas: 10
    target_cpu_utilization: 70
    target_memory_utilization: 80
    scale_up_stabilization: 60s
    scale_down_stabilization: 300s

# 特性开关
feature_flags:
  enable_agi: true
  enable_meta_learning: true
  enable_self_evolution: true
  enable_hybrid_mode: true
  enable_advanced_caching: true
  enable_distributed_processing: true
  enable_auto_optimization: true
  enable_experimental_features: false