# 太上老君监控系统 AlertManager 配置

global:
  # SMTP 配置
  smtp_smarthost: 'localhost:587'
  smtp_from: 'monitoring@taishanglaojun.com'
  smtp_auth_username: 'monitoring@taishanglaojun.com'
  smtp_auth_password: 'your-email-password'
  
  # 默认接收者
  smtp_hello: 'localhost'
  
  # 解析超时
  resolve_timeout: 5m

# 模板文件
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# 路由配置
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  
  routes:
    # 严重告警立即发送
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    
    # 警告级别告警
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m
    
    # 信息级别告警
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 5m
      repeat_interval: 2h
    
    # 系统相关告警
    - match_re:
        service: ^(cpu|memory|disk|network)$
      receiver: 'system-alerts'
    
    # 应用相关告警
    - match_re:
        service: ^(api|web|database)$
      receiver: 'application-alerts'

# 接收者配置
receivers:
  # 默认接收者
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@taishanglaojun.com'
        subject: '[监控告警] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警详情: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ if .EndsAt }}解决时间: {{ .EndsAt.Format "2006-01-02 15:04:05" }}{{ end }}
          标签: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}
    
    webhook_configs:
      - url: 'http://monitoring:8080/api/v1/alerts/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'webhook'
            password: 'webhook123'

  # 严重告警接收者
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@taishanglaojun.com,ops@taishanglaojun.com'
        subject: '[严重告警] {{ .GroupLabels.alertname }}'
        body: |
          🚨 严重告警通知 🚨
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警详情: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          服务: {{ .Labels.service }}
          实例: {{ .Labels.instance }}
          {{ end }}
          
          请立即处理！
    
    # 钉钉通知（示例）
    webhook_configs:
      - url: 'https://oapi.dingtalk.com/robot/send?access_token=your-dingtalk-token'
        send_resolved: true
        http_config:
          headers:
            Content-Type: application/json
        title: '严重告警'
        text: |
          {{ range .Alerts }}
          告警: {{ .Annotations.summary }}
          详情: {{ .Annotations.description }}
          时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # 警告级别接收者
  - name: 'warning-alerts'
    email_configs:
      - to: 'ops@taishanglaojun.com'
        subject: '[警告] {{ .GroupLabels.alertname }}'
        body: |
          ⚠️ 警告通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警详情: {{ .Annotations.description }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # 信息级别接收者
  - name: 'info-alerts'
    email_configs:
      - to: 'dev@taishanglaojun.com'
        subject: '[信息] {{ .GroupLabels.alertname }}'
        body: |
          ℹ️ 信息通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警详情: {{ .Annotations.description }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # 系统告警接收者
  - name: 'system-alerts'
    email_configs:
      - to: 'sysadmin@taishanglaojun.com'
        subject: '[系统告警] {{ .GroupLabels.alertname }}'
        body: |
          🖥️ 系统告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警详情: {{ .Annotations.description }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          主机: {{ .Labels.instance }}
          {{ end }}

  # 应用告警接收者
  - name: 'application-alerts'
    email_configs:
      - to: 'dev@taishanglaojun.com'
        subject: '[应用告警] {{ .GroupLabels.alertname }}'
        body: |
          📱 应用告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警详情: {{ .Annotations.description }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          服务: {{ .Labels.service }}
          {{ end }}

# 抑制规则
inhibit_rules:
  # 如果有严重告警，抑制同一服务的警告告警
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance']
  
  # 如果服务不可用，抑制该服务的其他告警
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      service: '.*'
    equal: ['service']