apiVersion: v1
kind: Namespace
metadata:
  name: taishanglaojun
  labels:
    name: taishanglaojun
    app: taishanglaojun-platform
    version: v1.0.0
  annotations:
    description: "太上老君AI平台命名空间"
    contact: "admin@taishanglaojun.com"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: taishanglaojun-quota
  namespace: taishanglaojun
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: taishanglaojun-limits
  namespace: taishanglaojun
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container