// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: consciousness.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthResponse 健康检查响?
type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version   string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consciousness_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consciousness_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_consciousness_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// StatsResponse 统计响应
type StatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveSessions   int64                  `protobuf:"varint,1,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	TotalRequests    int64                  `protobuf:"varint,2,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	AverageLatency   *durationpb.Duration   `protobuf:"bytes,3,opt,name=average_latency,json=averageLatency,proto3" json:"average_latency,omitempty"`
	LastRequestTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_request_time,json=lastRequestTime,proto3" json:"last_request_time,omitempty"`
	ServiceStartTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=service_start_time,json=serviceStartTime,proto3" json:"service_start_time,omitempty"`
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consciousness_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consciousness_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_consciousness_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetActiveSessions() int64 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *StatsResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *StatsResponse) GetAverageLatency() *durationpb.Duration {
	if x != nil {
		return x.AverageLatency
	}
	return nil
}

func (x *StatsResponse) GetLastRequestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRequestTime
	}
	return nil
}

func (x *StatsResponse) GetServiceStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServiceStartTime
	}
	return nil
}

// ConsciousnessRequest 意识处理请求
type ConsciousnessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string            `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input     string            `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Context   map[string]string `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Options   *ProcessOptions   `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *ConsciousnessRequest) Reset() {
	*x = ConsciousnessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consciousness_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsciousnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsciousnessRequest) ProtoMessage() {}

func (x *ConsciousnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consciousness_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsciousnessRequest.ProtoReflect.Descriptor instead.
func (*ConsciousnessRequest) Descriptor() ([]byte, []int) {
	return file_consciousness_proto_rawDescGZIP(), []int{2}
}

func (x *ConsciousnessRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConsciousnessRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ConsciousnessRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ConsciousnessRequest) GetOptions() *ProcessOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// ProcessOptions 处理选项
type ProcessOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnableFusion     bool  `protobuf:"varint,1,opt,name=enable_fusion,json=enableFusion,proto3" json:"enable_fusion,omitempty"`
	EnableEvolution  bool  `protobuf:"varint,2,opt,name=enable_evolution,json=enableEvolution,proto3" json:"enable_evolution,omitempty"`
	EnableGeneticOps bool  `protobuf:"varint,3,opt,name=enable_genetic_ops,json=enableGeneticOps,proto3" json:"enable_genetic_ops,omitempty"`
	Timeout          int32 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *ProcessOptions) Reset() {
	*x = ProcessOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consciousness_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOptions) ProtoMessage() {}

func (x *ProcessOptions) ProtoReflect() protoreflect.Message {
	mi := &file_consciousness_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOptions.ProtoReflect.Descriptor instead.
func (*ProcessOptions) Descriptor() ([]byte, []int) {
	return file_consciousness_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessOptions) GetEnableFusion() bool {
	if x != nil {
		return x.EnableFusion
	}
	return false
}

func (x *ProcessOptions) GetEnableEvolution() bool {
	if x != nil {
		return x.EnableEvolution
	}
	return false
}

func (x *ProcessOptions) GetEnableGeneticOps() bool {
	if x != nil {
		return x.EnableGeneticOps
	}
	return false
}

func (x *ProcessOptions) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// ConsciousnessResponse 意识处理响应
type ConsciousnessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId   string               `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Output      string               `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Metadata    map[string]string    `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ProcessTime *durationpb.Duration `protobuf:"bytes,4,opt,name=process_time,json=processTime,proto3" json:"process_time,omitempty"`
	Success     bool                 `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Error       string               `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ConsciousnessResponse) Reset() {
	*x = ConsciousnessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consciousness_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsciousnessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsciousnessResponse) ProtoMessage() {}

func (x *ConsciousnessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consciousness_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsciousnessResponse.ProtoReflect.Descriptor instead.
func (*ConsciousnessResponse) Descriptor() ([]byte, []int) {
	return file_consciousness_proto_rawDescGZIP(), []int{4}
}

func (x *ConsciousnessResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConsciousnessResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ConsciousnessResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ConsciousnessResponse) GetProcessTime() *durationpb.Duration {
	if x != nil {
		return x.ProcessTime
	}
	return nil
}

func (x *ConsciousnessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsciousnessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_consciousness_proto protoreflect.FileDescriptor

var file_consciousness_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x73, 0x63, 0x69, 0x6f, 0x75, 0x73, 0x6e, 0x65, 0x73, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x63, 0x69, 0x6f, 0x75, 0x73,
	0x6e, 0x65, 0x73, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x6f, 0x64, 0x65, 0x74, 0x61, 0x6f, 0x69, 0x73, 0x74, 0x2f, 0x74, 0x61, 0x69, 0x73, 0x68, 0x61,
	0x6e, 0x67, 0x6c, 0x61, 0x6f, 0x6a, 0x75, 0x6e, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x63, 0x69, 0x6f, 0x75, 0x73,
	0x6e, 0x65, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_consciousness_proto_rawDescOnce sync.Once
	file_consciousness_proto_rawDescData = file_consciousness_proto_rawDesc
)

func file_consciousness_proto_rawDescGZIP() []byte {
	file_consciousness_proto_rawDescOnce.Do(func() {
		file_consciousness_proto_rawDescData = protoimpl.X.CompressGZIP(file_consciousness_proto_rawDescData)
	})
	return file_consciousness_proto_rawDescData
}

var file_consciousness_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_consciousness_proto_goTypes = []interface{}{
	(*HealthResponse)(nil),        // 0: consciousness.HealthResponse
	(*StatsResponse)(nil),         // 1: consciousness.StatsResponse
	(*ConsciousnessRequest)(nil),  // 2: consciousness.ConsciousnessRequest
	(*ProcessOptions)(nil),        // 3: consciousness.ProcessOptions
	(*ConsciousnessResponse)(nil), // 4: consciousness.ConsciousnessResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 6: google.protobuf.Duration
}
var file_consciousness_proto_depIdxs = []int32{
	5, // 0: consciousness.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	6, // 1: consciousness.StatsResponse.average_latency:type_name -> google.protobuf.Duration
	5, // 2: consciousness.StatsResponse.last_request_time:type_name -> google.protobuf.Timestamp
	5, // 3: consciousness.StatsResponse.service_start_time:type_name -> google.protobuf.Timestamp
	3, // 4: consciousness.ConsciousnessRequest.options:type_name -> consciousness.ProcessOptions
	6, // 5: consciousness.ConsciousnessResponse.process_time:type_name -> google.protobuf.Duration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_consciousness_proto_init() }
func file_consciousness_proto_init() {
	if File_consciousness_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_consciousness_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consciousness_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consciousness_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsciousnessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consciousness_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consciousness_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsciousnessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consciousness_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consciousness_proto_goTypes,
		DependencyIndexes: file_consciousness_proto_depIdxs,
		MessageInfos:      file_consciousness_proto_msgTypes,
	}.Build()
	File_consciousness_proto = out.File
	file_consciousness_proto_rawDesc = nil
	file_consciousness_proto_goTypes = nil
}

