# Prometheus配置文件 - API Gateway监控

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'api-gateway'
    environment: 'development'

# 规则文件
rule_files:
  - "alert_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # API Gateway监控
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    metrics_path: /metrics

  # Node Exporter (如果有的话)
  - job_name: 'node-exporter'
    static_configs:
      - targets: []
        # - node-exporter:9100
    scrape_interval: 15s

  # 后端服务监控
  - job_name: 'backend-services'
    static_configs:
      - targets: 
        - 'mock-auth-service:80'
        - 'mock-user-service:80'
        - 'mock-admin-service:80'
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # 服务发现配置 (Consul)
  # - job_name: 'consul-services'
  #   consul_sd_configs:
  #     - server: 'consul:8500'
  #       services: []
  #   relabel_configs:
  #     - source_labels: [__meta_consul_service]
  #       target_label: job
  #     - source_labels: [__meta_consul_service_id]
  #       target_label: instance
  #     - source_labels: [__meta_consul_tags]
  #       target_label: tags
  #       regex: ,(.+),
  #       replacement: ${1}
  #     - source_labels: [__meta_consul_dc]
  #       target_label: datacenter

  # Kubernetes服务发现 (如果部署在K8s中)
  # - job_name: 'kubernetes-pods'
  #   kubernetes_sd_configs:
  #     - role: pod
  #   relabel_configs:
  #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
  #       action: keep
  #       regex: true
  #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
  #       action: replace
  #       target_label: __metrics_path__
  #       regex: (.+)
  #     - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
  #       action: replace
  #       regex: ([^:]+)(?::\d+)?;(\d+)
  #       replacement: $1:$2
  #       target_label: __address__
  #     - action: labelmap
  #       regex: __meta_kubernetes_pod_label_(.+)
  #     - source_labels: [__meta_kubernetes_namespace]
  #       action: replace
  #       target_label: kubernetes_namespace
  #     - source_labels: [__meta_kubernetes_pod_name]
  #       action: replace
  #       target_label: kubernetes_pod_name

# 远程写入配置 (可选)
# remote_write:
#   - url: "http://remote-storage:9201/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# 远程读取配置 (可选)
# remote_read:
#   - url: "http://remote-storage:9201/read"