{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-db
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-redis
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-jwt
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.security.jwt.secret | b64enc | quote }}

{{- if .Values.security.encryption.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-encryption
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ .Values.security.encryption.key | b64enc | quote }}
{{- end }}

{{- if .Values.secrets.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-custom
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}