# 核心服务配置文件
server:
  name: "core-services"
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # debug, release, test
  timeout: 30s
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["*"]
  request_logging: true

# 主数据库配置 (支持 postgres, mysql, sqlserver)
database:
  driver: "postgres"  # postgres, mysql, sqlserver, mssql
  host: "localhost"
  port: 5432
  database: "taishang_core"
  username: "postgres"
  password: "password"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s
  ssl_mode: "disable"
  connect_timeout: 10s

# MySQL 数据库配置示例
database_mysql:
  driver: "mysql"
  host: "localhost"
  port: 3306
  database: "taishang_core"
  username: "root"
  password: "password"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s
  connect_timeout: 10s

# SQL Server 数据库配置示例
database_sqlserver:
  driver: "sqlserver"
  host: "localhost"
  port: 1433
  database: "taishang_core"
  username: "sa"
  password: "Password123!"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s
  connect_timeout: 10s

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s

# AI服务配置
ai:
  providers:
    openai:
      api_key: ""
      base_url: "https://api.openai.com/v1"
      model: "gpt-3.5-turbo"
      timeout: 30s
    azure:
      api_key: ""
      endpoint: ""
      deployment: ""
      api_version: "2023-05-15"
      timeout: 30s
    baidu:
      api_key: ""
      secret_key: ""
      timeout: 30s

# 日志配置
logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, console
  output: "stdout"  # stdout, file
  file:
    path: "./logs/core-services.log"
    max_size: 100  # MB
    max_backups: 10
    max_age: 30  # days
    compress: true