apiVersion: v1
kind: Namespace
metadata:
  name: taishanglaojun
  labels:
    name: taishanglaojun
    app.kubernetes.io/name: taishanglaojun
    app.kubernetes.io/component: ai-platform
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "太上老君AI平台命名空间"
    contact: "taishanglaojun-team@example.com"
    version: "1.0.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: taishanglaojun-quota
  namespace: taishanglaojun
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: taishanglaojun-limits
  namespace: taishanglaojun
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim