# 太上老君监控系统 Kubernetes Secret 配置

apiVersion: v1
kind: Secret
metadata:
  name: taishanglaojun-monitoring-secrets
  namespace: taishanglaojun-monitoring
  labels:
    app.kubernetes.io/name: taishanglaojun-monitoring
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: taishanglaojun
type: Opaque
data:
  # InfluxDB Token (base64 encoded: monitoring-token-123456789)
  influxdb-token: bW9uaXRvcmluZy10b2tlbi0xMjM0NTY3ODk=
  
  # SMTP Password (base64 encoded: your-smtp-password)
  smtp-password: eW91ci1zbXRwLXBhc3N3b3Jk
  
  # Database Password (base64 encoded: your-db-password)
  db-password: eW91ci1kYi1wYXNzd29yZA==
  
  # JWT Secret (base64 encoded: your-jwt-secret-key)
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleQ==
  
  # API Key (base64 encoded: your-api-key)
  api-key: eW91ci1hcGkta2V5

---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
  namespace: taishanglaojun-monitoring
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: taishanglaojun
type: Opaque
data:
  # Admin Username (base64 encoded: admin)
  admin-username: YWRtaW4=
  
  # Admin Password (base64 encoded: admin123)
  admin-password: YWRtaW4xMjM=
  
  # Admin Token (base64 encoded: monitoring-token-123456789)
  admin-token: bW9uaXRvcmluZy10b2tlbi0xMjM0NTY3ODk=

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: taishanglaojun-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: taishanglaojun
type: Opaque
data:
  # Admin Username (base64 encoded: admin)
  admin-username: YWRtaW4=
  
  # Admin Password (base64 encoded: admin123)
  admin-password: YWRtaW4xMjM=

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: taishanglaojun-monitoring
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: taishanglaojun
type: Opaque
data:
  # Redis Password (base64 encoded: redis123)
  redis-password: cmVkaXMxMjM=

---
# TLS Secret for HTTPS (需要替换为实际的证书)
apiVersion: v1
kind: Secret
metadata:
  name: taishanglaojun-monitoring-tls
  namespace: taishanglaojun-monitoring
  labels:
    app.kubernetes.io/name: taishanglaojun-monitoring
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: taishanglaojun
type: kubernetes.io/tls
data:
  # 需要替换为实际的 TLS 证书和私钥 (base64 encoded)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t