{{/*
太上老君监控系统 PodDisruptionBudget 模板
*/}}
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "taishanglaojun-monitoring.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "taishanglaojun-monitoring.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "taishanglaojun-monitoring.selectorLabels" . | nindent 6 }}
{{- end }}