{{/*
太上老君监控系统 RBAC 模板
*/}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "taishanglaojun-monitoring.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "taishanglaojun-monitoring.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "taishanglaojun-monitoring.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "taishanglaojun-monitoring.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "taishanglaojun-monitoring.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "taishanglaojun-monitoring.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- if .Values.rbac.clusterRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "taishanglaojun-monitoring.fullname" . }}-cluster
  labels:
    {{- include "taishanglaojun-monitoring.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "taishanglaojun-monitoring.fullname" . }}-cluster
  labels:
    {{- include "taishanglaojun-monitoring.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "taishanglaojun-monitoring.fullname" . }}-cluster
subjects:
  - kind: ServiceAccount
    name: {{ include "taishanglaojun-monitoring.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}