{{/*
太上老君监控系统 Service 模板
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taishanglaojun-monitoring.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "taishanglaojun-monitoring.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "taishanglaojun-monitoring.selectorLabels" . | nindent 4 }}

{{- if .Values.service.headless }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taishanglaojun-monitoring.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "taishanglaojun-monitoring.labels" . | nindent 4 }}
    service-type: headless
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "taishanglaojun-monitoring.selectorLabels" . | nindent 4 }}
{{- end }}