# 太上老君监控系统 Deployment 补丁配置

apiVersion: apps/v1
kind: Deployment
metadata:
  name: taishanglaojun-monitoring
  namespace: taishanglaojun-monitoring
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        fluentd.org/exclude: "false"
    spec:
      containers:
        - name: monitoring
          env:
            - name: MONITORING_SERVICE_ENVIRONMENT
              value: "production"
            - name: MONITORING_SERVICE_LOG_LEVEL
              value: "info"
            - name: MONITORING_METRICS_ENABLED
              value: "true"
            - name: MONITORING_TRACING_ENABLED
              value: "true"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi