# 太上老君监控系统 Service 补丁配置

apiVersion: v1
kind: Service
metadata:
  name: taishanglaojun-monitoring
  namespace: taishanglaojun-monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP