# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ai_service_pb2 as ai__service__pb2


class VectorServiceStub(object):
    """Vector database service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/ai.VectorService/HealthCheck',
                request_serializer=ai__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ai__service__pb2.HealthCheckResponse.FromString,
                )
        self.CreateCollection = channel.unary_unary(
                '/ai.VectorService/CreateCollection',
                request_serializer=ai__service__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=ai__service__pb2.CreateCollectionResponse.FromString,
                )
        self.DropCollection = channel.unary_unary(
                '/ai.VectorService/DropCollection',
                request_serializer=ai__service__pb2.DropCollectionRequest.SerializeToString,
                response_deserializer=ai__service__pb2.DropCollectionResponse.FromString,
                )
        self.HasCollection = channel.unary_unary(
                '/ai.VectorService/HasCollection',
                request_serializer=ai__service__pb2.HasCollectionRequest.SerializeToString,
                response_deserializer=ai__service__pb2.HasCollectionResponse.FromString,
                )
        self.DescribeCollection = channel.unary_unary(
                '/ai.VectorService/DescribeCollection',
                request_serializer=ai__service__pb2.DescribeCollectionRequest.SerializeToString,
                response_deserializer=ai__service__pb2.DescribeCollectionResponse.FromString,
                )
        self.LoadCollection = channel.unary_unary(
                '/ai.VectorService/LoadCollection',
                request_serializer=ai__service__pb2.LoadCollectionRequest.SerializeToString,
                response_deserializer=ai__service__pb2.LoadCollectionResponse.FromString,
                )
        self.ReleaseCollection = channel.unary_unary(
                '/ai.VectorService/ReleaseCollection',
                request_serializer=ai__service__pb2.ReleaseCollectionRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ReleaseCollectionResponse.FromString,
                )
        self.GetCollectionStatistics = channel.unary_unary(
                '/ai.VectorService/GetCollectionStatistics',
                request_serializer=ai__service__pb2.GetCollectionStatisticsRequest.SerializeToString,
                response_deserializer=ai__service__pb2.GetCollectionStatisticsResponse.FromString,
                )
        self.ListCollections = channel.unary_unary(
                '/ai.VectorService/ListCollections',
                request_serializer=ai__service__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ListCollectionsResponse.FromString,
                )
        self.CreateIndex = channel.unary_unary(
                '/ai.VectorService/CreateIndex',
                request_serializer=ai__service__pb2.CreateIndexRequest.SerializeToString,
                response_deserializer=ai__service__pb2.CreateIndexResponse.FromString,
                )
        self.DropIndex = channel.unary_unary(
                '/ai.VectorService/DropIndex',
                request_serializer=ai__service__pb2.DropIndexRequest.SerializeToString,
                response_deserializer=ai__service__pb2.DropIndexResponse.FromString,
                )
        self.DescribeIndex = channel.unary_unary(
                '/ai.VectorService/DescribeIndex',
                request_serializer=ai__service__pb2.DescribeIndexRequest.SerializeToString,
                response_deserializer=ai__service__pb2.DescribeIndexResponse.FromString,
                )
        self.Insert = channel.unary_unary(
                '/ai.VectorService/Insert',
                request_serializer=ai__service__pb2.InsertRequest.SerializeToString,
                response_deserializer=ai__service__pb2.InsertResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/ai.VectorService/Delete',
                request_serializer=ai__service__pb2.DeleteRequest.SerializeToString,
                response_deserializer=ai__service__pb2.DeleteResponse.FromString,
                )
        self.Search = channel.unary_unary(
                '/ai.VectorService/Search',
                request_serializer=ai__service__pb2.SearchRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SearchResponse.FromString,
                )
        self.GetById = channel.unary_unary(
                '/ai.VectorService/GetById',
                request_serializer=ai__service__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=ai__service__pb2.GetByIdResponse.FromString,
                )
        self.Compact = channel.unary_unary(
                '/ai.VectorService/Compact',
                request_serializer=ai__service__pb2.CompactRequest.SerializeToString,
                response_deserializer=ai__service__pb2.CompactResponse.FromString,
                )


class VectorServiceServicer(object):
    """Vector database service
    """

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Collection operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIndex(self, request, context):
        """Index operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Data operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compact(self, request, context):
        """Collection operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ai__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=ai__service__pb2.HealthCheckResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=ai__service__pb2.CreateCollectionRequest.FromString,
                    response_serializer=ai__service__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'DropCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DropCollection,
                    request_deserializer=ai__service__pb2.DropCollectionRequest.FromString,
                    response_serializer=ai__service__pb2.DropCollectionResponse.SerializeToString,
            ),
            'HasCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.HasCollection,
                    request_deserializer=ai__service__pb2.HasCollectionRequest.FromString,
                    response_serializer=ai__service__pb2.HasCollectionResponse.SerializeToString,
            ),
            'DescribeCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeCollection,
                    request_deserializer=ai__service__pb2.DescribeCollectionRequest.FromString,
                    response_serializer=ai__service__pb2.DescribeCollectionResponse.SerializeToString,
            ),
            'LoadCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadCollection,
                    request_deserializer=ai__service__pb2.LoadCollectionRequest.FromString,
                    response_serializer=ai__service__pb2.LoadCollectionResponse.SerializeToString,
            ),
            'ReleaseCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseCollection,
                    request_deserializer=ai__service__pb2.ReleaseCollectionRequest.FromString,
                    response_serializer=ai__service__pb2.ReleaseCollectionResponse.SerializeToString,
            ),
            'GetCollectionStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionStatistics,
                    request_deserializer=ai__service__pb2.GetCollectionStatisticsRequest.FromString,
                    response_serializer=ai__service__pb2.GetCollectionStatisticsResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=ai__service__pb2.ListCollectionsRequest.FromString,
                    response_serializer=ai__service__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'CreateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIndex,
                    request_deserializer=ai__service__pb2.CreateIndexRequest.FromString,
                    response_serializer=ai__service__pb2.CreateIndexResponse.SerializeToString,
            ),
            'DropIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DropIndex,
                    request_deserializer=ai__service__pb2.DropIndexRequest.FromString,
                    response_serializer=ai__service__pb2.DropIndexResponse.SerializeToString,
            ),
            'DescribeIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeIndex,
                    request_deserializer=ai__service__pb2.DescribeIndexRequest.FromString,
                    response_serializer=ai__service__pb2.DescribeIndexResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=ai__service__pb2.InsertRequest.FromString,
                    response_serializer=ai__service__pb2.InsertResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=ai__service__pb2.DeleteRequest.FromString,
                    response_serializer=ai__service__pb2.DeleteResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=ai__service__pb2.SearchRequest.FromString,
                    response_serializer=ai__service__pb2.SearchResponse.SerializeToString,
            ),
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=ai__service__pb2.GetByIdRequest.FromString,
                    response_serializer=ai__service__pb2.GetByIdResponse.SerializeToString,
            ),
            'Compact': grpc.unary_unary_rpc_method_handler(
                    servicer.Compact,
                    request_deserializer=ai__service__pb2.CompactRequest.FromString,
                    response_serializer=ai__service__pb2.CompactResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.VectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VectorService(object):
    """Vector database service
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/HealthCheck',
            ai__service__pb2.HealthCheckRequest.SerializeToString,
            ai__service__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/CreateCollection',
            ai__service__pb2.CreateCollectionRequest.SerializeToString,
            ai__service__pb2.CreateCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DropCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/DropCollection',
            ai__service__pb2.DropCollectionRequest.SerializeToString,
            ai__service__pb2.DropCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HasCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/HasCollection',
            ai__service__pb2.HasCollectionRequest.SerializeToString,
            ai__service__pb2.HasCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescribeCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/DescribeCollection',
            ai__service__pb2.DescribeCollectionRequest.SerializeToString,
            ai__service__pb2.DescribeCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/LoadCollection',
            ai__service__pb2.LoadCollectionRequest.SerializeToString,
            ai__service__pb2.LoadCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleaseCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/ReleaseCollection',
            ai__service__pb2.ReleaseCollectionRequest.SerializeToString,
            ai__service__pb2.ReleaseCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCollectionStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/GetCollectionStatistics',
            ai__service__pb2.GetCollectionStatisticsRequest.SerializeToString,
            ai__service__pb2.GetCollectionStatisticsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/ListCollections',
            ai__service__pb2.ListCollectionsRequest.SerializeToString,
            ai__service__pb2.ListCollectionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/CreateIndex',
            ai__service__pb2.CreateIndexRequest.SerializeToString,
            ai__service__pb2.CreateIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DropIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/DropIndex',
            ai__service__pb2.DropIndexRequest.SerializeToString,
            ai__service__pb2.DropIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescribeIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/DescribeIndex',
            ai__service__pb2.DescribeIndexRequest.SerializeToString,
            ai__service__pb2.DescribeIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/Insert',
            ai__service__pb2.InsertRequest.SerializeToString,
            ai__service__pb2.InsertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/Delete',
            ai__service__pb2.DeleteRequest.SerializeToString,
            ai__service__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/Search',
            ai__service__pb2.SearchRequest.SerializeToString,
            ai__service__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/GetById',
            ai__service__pb2.GetByIdRequest.SerializeToString,
            ai__service__pb2.GetByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Compact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.VectorService/Compact',
            ai__service__pb2.CompactRequest.SerializeToString,
            ai__service__pb2.CompactResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ModelServiceStub(object):
    """Model service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/ai.ModelService/HealthCheck',
                request_serializer=ai__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ai__service__pb2.HealthCheckResponse.FromString,
                )
        self.RegisterModel = channel.unary_unary(
                '/ai.ModelService/RegisterModel',
                request_serializer=ai__service__pb2.RegisterModelRequest.SerializeToString,
                response_deserializer=ai__service__pb2.RegisterModelResponse.FromString,
                )
        self.UpdateModel = channel.unary_unary(
                '/ai.ModelService/UpdateModel',
                request_serializer=ai__service__pb2.UpdateModelRequest.SerializeToString,
                response_deserializer=ai__service__pb2.UpdateModelResponse.FromString,
                )
        self.UnregisterModel = channel.unary_unary(
                '/ai.ModelService/UnregisterModel',
                request_serializer=ai__service__pb2.UnregisterModelRequest.SerializeToString,
                response_deserializer=ai__service__pb2.UnregisterModelResponse.FromString,
                )
        self.ListModels = channel.unary_unary(
                '/ai.ModelService/ListModels',
                request_serializer=ai__service__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ListModelsResponse.FromString,
                )
        self.GetModel = channel.unary_unary(
                '/ai.ModelService/GetModel',
                request_serializer=ai__service__pb2.GetModelRequest.SerializeToString,
                response_deserializer=ai__service__pb2.GetModelResponse.FromString,
                )
        self.LoadModel = channel.unary_unary(
                '/ai.ModelService/LoadModel',
                request_serializer=ai__service__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=ai__service__pb2.LoadModelResponse.FromString,
                )
        self.UnloadModel = channel.unary_unary(
                '/ai.ModelService/UnloadModel',
                request_serializer=ai__service__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=ai__service__pb2.UnloadModelResponse.FromString,
                )
        self.GetModelStatus = channel.unary_unary(
                '/ai.ModelService/GetModelStatus',
                request_serializer=ai__service__pb2.GetModelStatusRequest.SerializeToString,
                response_deserializer=ai__service__pb2.GetModelStatusResponse.FromString,
                )
        self.GenerateText = channel.unary_unary(
                '/ai.ModelService/GenerateText',
                request_serializer=ai__service__pb2.TextGenerationRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TextGenerationResponse.FromString,
                )
        self.GenerateEmbedding = channel.unary_unary(
                '/ai.ModelService/GenerateEmbedding',
                request_serializer=ai__service__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=ai__service__pb2.EmbeddingResponse.FromString,
                )


class ModelServiceServicer(object):
    """Model service
    """

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterModel(self, request, context):
        """Model management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Model operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateText(self, request, context):
        """Inference operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ai__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=ai__service__pb2.HealthCheckResponse.SerializeToString,
            ),
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=ai__service__pb2.RegisterModelRequest.FromString,
                    response_serializer=ai__service__pb2.RegisterModelResponse.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=ai__service__pb2.UpdateModelRequest.FromString,
                    response_serializer=ai__service__pb2.UpdateModelResponse.SerializeToString,
            ),
            'UnregisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterModel,
                    request_deserializer=ai__service__pb2.UnregisterModelRequest.FromString,
                    response_serializer=ai__service__pb2.UnregisterModelResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=ai__service__pb2.ListModelsRequest.FromString,
                    response_serializer=ai__service__pb2.ListModelsResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=ai__service__pb2.GetModelRequest.FromString,
                    response_serializer=ai__service__pb2.GetModelResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=ai__service__pb2.LoadModelRequest.FromString,
                    response_serializer=ai__service__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=ai__service__pb2.UnloadModelRequest.FromString,
                    response_serializer=ai__service__pb2.UnloadModelResponse.SerializeToString,
            ),
            'GetModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStatus,
                    request_deserializer=ai__service__pb2.GetModelStatusRequest.FromString,
                    response_serializer=ai__service__pb2.GetModelStatusResponse.SerializeToString,
            ),
            'GenerateText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=ai__service__pb2.TextGenerationRequest.FromString,
                    response_serializer=ai__service__pb2.TextGenerationResponse.SerializeToString,
            ),
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=ai__service__pb2.EmbeddingRequest.FromString,
                    response_serializer=ai__service__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Model service
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.ModelService/HealthCheck',
            ai__service__pb2.HealthCheckRequest.SerializeToString,
            ai__service__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.ModelService/RegisterModel',
            ai__service__pb2.RegisterModelRequest.SerializeToString,
            ai__service__pb2.RegisterModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.ModelService/UpdateModel',
            ai__service__pb2.UpdateModelRequest.SerializeToString,
            ai__service__pb2.UpdateModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnregisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.ModelService/UnregisterModel',
            ai__service__pb2.UnregisterModelRequest.SerializeToString,
            ai__service__pb2.UnregisterModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.ModelService/ListModels',
            ai__service__pb2.ListModelsRequest.SerializeToString,
            ai__service__pb2.ListModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.ModelService/GetModel',
            ai__service__pb2.GetModelRequest.SerializeToString,
            ai__service__pb2.GetModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.ModelService/LoadModel',
            ai__service__pb2.LoadModelRequest.SerializeToString,
            ai__service__pb2.LoadModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.ModelService/UnloadModel',
            ai__service__pb2.UnloadModelRequest.SerializeToString,
            ai__service__pb2.UnloadModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.ModelService/GetModelStatus',
            ai__service__pb2.GetModelStatusRequest.SerializeToString,
            ai__service__pb2.GetModelStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.ModelService/GenerateText',
            ai__service__pb2.TextGenerationRequest.SerializeToString,
            ai__service__pb2.TextGenerationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.ModelService/GenerateEmbedding',
            ai__service__pb2.EmbeddingRequest.SerializeToString,
            ai__service__pb2.EmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
